In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("googleplaystore.csv")
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,yrar
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,7,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,15,1,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,1,8,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,8,6,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,20,6,2018

In [3]:
df.shape

(10840, 16)

In [4]:
df.drop(columns=['day','month','yrar'])

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10835,Sya9a Maroc - FR,FAMILY,4.5,38,53.0,5000,Free,0.0,Everyone,Education,2017-07-25,1.48,4.1 and up
10836,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6,100,Free,0.0,Everyone,Education,2018-07-06,1.0,4.1 and up
10837,Parkinson Exercices FR,MEDICAL,NaN,3,9.5,1000,Free,0.0,Everyone,Medical,2017-01-20,1.0,2.2 and up
10838,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,0.0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device
10839,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19.0,10000000,Free,0.0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device

In [5]:
df.shape

(10840, 16)

In [6]:
df.info()
# ver stands for version

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10840 entries, 0 to 10839
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  object
 1   Category        10840 non-null  object
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int64
 4   Size            9145 non-null   float64
 5   Installs        10840 non-null  int64
 6   Type            10839 non-null  object
 7   Price           10840 non-null  float64
 8   Content Rating  10840 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10840 non-null  object
 11  Current Ver     10832 non-null  object
 12  Android Ver     10838 non-null  object
 13  day             10840 non-null  int64
 14  month           10840 non-null  int64
 15  yrar            10840 non-null  int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.3+ MB

In [7]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size              1695
Installs             0
Type                 1
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          8
Android Ver          2
day                  0
month                0
yrar                 0
dtype: int64

In [8]:
df.describe()

,Rating,Reviews,Size,Installs,Price,day,month,yrar
count,9366.000000,1.084000e+04,9145.000000,1.084000e+04,10840.000000,10840.000000,10840.000000,10840.000000
mean,4.191757,4.441529e+05,21.517458,1.546434e+07,1.027368,15.609041,6.422325,2017.399723
std,0.515219,2.927761e+06,22.588038,8.502936e+07,15.949703,9.561621,2.578388,1.100914
min,1.000000,0.000000e+00,0.011000,0.000000e+00,0.000000,1.000000,1.000000,2010.000000
25%,4.000000,3.800000e+01,4.900000,1.000000e+03,0.000000,6.000000,5.000000,2017.000000
50%,4.300000,2.094000e+03,13.000000,1.000000e+05,0.000000,16.000000,7.000000,2018.000000
75%,4.500000,5.477550e+04,30.000000,5.000000e+06,0.000000,24.000000,8.000000,2018.000000
max,5.000000,7.815831e+07,100.000000,1.000000e+09,400.000000,31.000000,12.000000,2018.000000

In [9]:
# check duplicate values
df.duplicated().sum()

483

In [10]:
#see duplicated dataframes
df[df.duplicated()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,yrar
229,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,NaN,5000000,Free,0.0,Everyone,Business,2018-02-26,Varies with device,4.0.3 and up,26,2,2018
236,Box,BUSINESS,4.2,159872,NaN,10000000,Free,0.0,Everyone,Business,2018-07-31,Varies with device,Varies with device,31,7,2018
239,Google My Business,BUSINESS,4.4,70991,NaN,5000000,Free,0.0,Everyone,Business,2018-07-24,2.19.0.204537701,4.4 and up,24,7,2018
256,ZOOM Cloud Meetings,BUSINESS,4.4,31614,37.0,10000000,Free,0.0,Everyone,Business,2018-07-20,4.1.28165.0716,4.0 and up,20,7,2018
261,join.me - Simple Meetings,BUSINESS,4.0,6989,NaN,1000000,Free,0.0,Everyone,Business,2018-07-16,4.3.0.508,4.4 and up,16,7,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8643,Wunderlist: To-Do List & Tasks,PRODUCTIVITY,4.6,404610,NaN,10000000,Free,0.0,Everyone,Productivity,2018-04-06,Varies with device,Varies with device,6,4,2018
8654,"TickTick: To Do List with Reminder, Day Planner",PRODUCTIVITY,4.6,25370,NaN,1000000,Free,0.0,Everyone,Productivity,2018-08-06,Varies with device,Varies with device,6,8,2018
8658,ColorNote Notepad Notes,PRODUCTIVITY,4.6,2401017,NaN,100000000,Free,0.0,Everyone,Productivity,2018-06-27,Varies with device,Varies with device,27,6,2018
10049,Airway Ex - Intubate. Anesthetize. Train.,MEDICAL,4.3,123,86.0,10000,Free,0.0,Everyone,Medical,2018-06-01,0.6.88,5.0 and up,1,6,2018
10767,AAFP,MEDICAL,3.8,63,24.0,10000,Free,0.0,Everyone,Medical,2018-06-22,2.3.1,5.0 and up,22,6,2018

In [11]:
# include all features
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
App,10840,9659,ROBLOX,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,10840,33,FAMILY,1972,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rating,9366,NaN,NaN,NaN,4.19176,0.515219,1,4,4.3,4.5,5
Reviews,10840,NaN,NaN,NaN,444153,2.92776e+06,0,38,2094,54775.5,7.81583e+07
Size,9145,NaN,NaN,NaN,21.5175,22.588,0.011,4.9,13,30,100
Installs,10840,NaN,NaN,NaN,1.54643e+07,8.50294e+07,0,1000,100000,5e+06,1e+09
Type,10839,2,Free,10039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Price,10840,NaN,NaN,NaN,1.02737,15.9497,0,0,0,0,400
Content Rating,10840,6,Everyone,8714,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Genres,10840,119,Tools,842,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Last Updated,10840,1377,2018-08-03,326,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Current Ver,10832,2831,Varies with device,1459,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Android Ver,10838,33,4.1 and up,2451,NaN,NaN,NaN,NaN,NaN,NaN,NaN
day,10840,NaN,NaN,NaN,15.609,9.56162,1,6,16,24,31
month,10840,NaN,NaN,NaN,6.42232,2.57839,1,5,7,8,12
yrar,10840,NaN,NaN,NaN,2017.4,1.10091,2010,2017,2018,2018,2018

In [12]:
#generate 10 randome sample
df.sample(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,yrar
6907,BW Mobilbanking für Smartphone und Tablet,FINANCE,4.1,2048,24.0,100000,Free,0.0,Everyone,Finance,2018-07-10,4.2.0,4.4 and up,10,7,2018
4041,Temple Run 2,GAME,4.3,8116142,62.0,500000000,Free,0.0,Everyone,Action,2018-07-05,1.49.1,4.0 and up,5,7,2018
225,Secure Folder,BUSINESS,3.8,14760,8.6,50000000,Free,0.0,Everyone,Business,2018-01-31,1.1.07.6,7.0 and up,31,1,2018
774,GMAT Math Flashcards,EDUCATION,4.4,1769,NaN,100000,Free,0.0,Everyone,Education,2018-07-11,Varies with device,Varies with device,11,7,2018
5047,Hesab.af - Send money in Afghanistan,FINANCE,4.7,51,11.0,1000,Free,0.0,Everyone,Finance,2018-04-15,1.4.0,4.1 and up,15,4,2018
5363,I Am Innocent,GAME,4.4,208501,56.0,1000000,Free,0.0,Teen,Adventure,2018-07-23,2.8.307,4.0.3 and up,23,7,2018
7202,ABAI CE Scanner,FAMILY,NaN,0,4.3,1000,Free,0.0,Everyone,Education,2018-01-23,1.3,4.1 and up,23,1,2018
6787,Mediatek SmartDevice,TOOLS,3.6,11187,7.3,1000000,Free,0.0,Everyone,Tools,2017-03-17,V1.7.6,4.0 and up,17,3,2017
10205,Puffin for Facebook,SOCIAL,4.0,10743,NaN,500000,Free,0.0,Teen,Social,2017-12-28,7.0.4.17908,4.1 and up,28,12,2017
133,Dresses Ideas & Fashions +3000,BEAUTY,4.5,473,8.2,100000,Free,0.0,Mature 17+,Beauty,2017-03-01,1.0.2.0,1.6 and up,1,3,2017

In [13]:
#focused on Reviews column its numeric feature but its given as object
df["Reviews"]

0           159
1           967
2         87510
3        215644
4           967
          ...
10835        38
10836         4
10837         3
10838       114
10839    398307
Name: Reviews, Length: 10840, dtype: int64

In [14]:
df["Reviews"].dtypes

dtype('int64')

In [15]:
df["Reviews"].shape

(10840,)

In [21]:
df['Reviews'] = df['Reviews'].astype(str)

In [22]:
df.Reviews.str.isnumeric().sum()

10840

In [23]:
df ['Reviews'].str.isnumeric().sum()

10840

In [24]:
df ['Reviews'].str.isnumeric()

0        True
1        True
2        True
3        True
4        True
         ...
10835    True
10836    True
10837    True
10838    True
10839    True
Name: Reviews, Length: 10840, dtype: bool

In [25]:
# see the negation
# where the value is numeric it gives false and vice versa
~df ['Reviews'].str.isnumeric()

0        False
1        False
2        False
3        False
4        False
         ...
10835    False
10836    False
10837    False
10838    False
10839    False
Name: Reviews, Length: 10840, dtype: bool

In [26]:
# datatype change from object to int
df.Reviews.str.isnumeric().sum().dtype

dtype('int64')

In [27]:
# gives true dataframes
df[df ['Reviews'].str.isnumeric()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,yrar
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,7,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,15,1,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,1,8,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,8,6,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,20,6,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10835,Sya9a Maroc - FR,FAMILY,4.5,38,53.0,5000,Free,0.0,Everyone,Education,2017-07-25,1.48,4.1 and up,25,7,2017
10836,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6,100,Free,0.0,Everyone,Education,2018-07-06,1.0,4.1 and up,6,7,2018
10837,Parkinson Exercices FR,MEDICAL,NaN,3,9.5,1000,Free,0.0,Everyone,Medical,2017-01-20,1.0,2.2 and up,20,1,2017
10838,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,NaN,1000,Free,0.0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device,19,1,2015
10839,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19.0,10000000,Free,0.0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device,25,7,2018

In [28]:
#one value is categorical  in int conversion 10841-10840
df[~df["Reviews"].str.isnumeric()]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver, day, month, yrar]
Index: []

In [29]:
#Create a copy of data set
df_copy=df.copy()

In [30]:
#remove the row with index 1042
df_copy=df_copy.drop(df_copy.index[10472])

In [31]:
df_copy.shape

(10839, 16)

In [32]:
# datatype is object 
df_copy["Reviews"].dtype

dtype('O')

In [33]:
# need to change data type
df_copy["Reviews"]=df_copy["Reviews"].astype('int')

In [34]:
df_copy.shape

(10839, 16)

In [35]:
# datatype changed
df_copy["Reviews"].dtype

dtype('int32')

In [36]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10839 entries, 0 to 10839
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  object
 1   Category        10839 non-null  object
 2   Rating          9365 non-null   float64
 3   Reviews         10839 non-null  int32
 4   Size            9144 non-null   float64
 5   Installs        10839 non-null  int64
 6   Type            10838 non-null  object
 7   Price           10839 non-null  float64
 8   Content Rating  10839 non-null  object
 9   Genres          10839 non-null  object
 10  Last Updated    10839 non-null  object
 11  Current Ver     10831 non-null  object
 12  Android Ver     10837 non-null  object
 13  day             10839 non-null  int64
 14  month           10839 non-null  int64
 15  yrar            10839 non-null  int64
dtypes: float64(3), int32(1), int64(4), object(8)
memory usage: 1.4+ MB

In [37]:
df_copy['Size']

0        19.0
1        14.0
2         8.7
3        25.0
4         2.8
         ...
10835    53.0
10836     3.6
10837     9.5
10838     NaN
10839    19.0
Name: Size, Length: 10839, dtype: float64

In [38]:
df_copy.duplicated().sum()

483

In [39]:
# find unique sizes
df_copy['Size'].unique()

array([1.90e+01, 1.40e+01, 8.70e+00, 2.50e+01, 2.80e+00, 5.60e+00,
       2.90e+01, 3.30e+01, 3.10e+00, 2.80e+01, 1.20e+01, 2.00e+01,
       2.10e+01, 3.70e+01, 2.70e+00, 5.50e+00, 1.70e+01, 3.90e+01,
       3.10e+01, 4.20e+00, 7.00e+00, 2.30e+01, 6.00e+00, 6.10e+00,
       4.60e+00, 9.20e+00, 5.20e+00, 1.10e+01, 2.40e+01,      nan,
       9.40e+00, 1.50e+01, 1.00e+01, 1.20e+00, 2.60e+01, 8.00e+00,
       7.90e+00, 5.60e+01, 5.70e+01, 3.50e+01, 5.40e+01, 2.01e-01,
       3.60e+00, 5.70e+00, 8.60e+00, 2.40e+00, 2.70e+01, 2.50e+00,
       1.60e+01, 3.40e+00, 8.90e+00, 3.90e+00, 2.90e+00, 3.80e+01,
       3.20e+01, 5.40e+00, 1.80e+01, 1.10e+00, 2.20e+00, 4.50e+00,
       9.80e+00, 5.20e+01, 9.00e+00, 6.70e+00, 3.00e+01, 2.60e+00,
       7.10e+00, 3.70e+00, 2.20e+01, 7.40e+00, 6.40e+00, 3.20e+00,
       8.20e+00, 9.90e+00, 4.90e+00, 9.50e+00, 5.00e+00, 5.90e+00,
       1.30e+01, 7.30e+01, 6.80e+00, 3.50e+00, 4.00e+00, 2.30e+00,
       7.20e+00, 2.10e+00, 4.20e+01, 7.30e+00, 9.10e+00, 5.50e+01,
       2.30e-02, 6.50e+00, 1.50e+00, 7.50e+00, 5.10e+01, 4.10e+01,
       4.80e+01, 8.50e+00, 4.60e+01, 8.30e+00, 4.30e+00, 4.70e+00,
       3.30e+00, 4.00e+01, 7.80e+00, 8.80e+00, 6.60e+00, 5.10e+00,
       6.10e+01, 6.60e+01, 7.90e-02, 8.40e+00, 1.18e-01, 4.40e+01,
       6.95e-01, 1.60e+00, 6.20e+00, 1.80e-02, 5.30e+01, 1.40e+00,
       3.00e+00, 5.80e+00, 3.80e+00, 9.60e+00, 4.50e+01, 6.30e+01,
       4.90e+01, 7.70e+01, 4.40e+00, 4.80e+00, 7.00e+01, 6.90e+00,
       9.30e+00, 8.10e+00, 3.60e+01, 8.40e+01, 9.70e+01, 2.00e+00,
       1.90e+00, 1.80e+00, 5.30e+00, 4.70e+01, 5.56e-01, 5.26e-01,
       7.60e+01, 7.60e+00, 5.90e+01, 9.70e+00, 7.80e+01, 7.20e+01,
       4.30e+01, 7.70e+00, 6.30e+00, 3.34e-01, 3.40e+01, 9.30e+01,
       6.50e+01, 7.90e+01, 1.00e+02, 5.80e+01, 5.00e+01, 6.80e+01,
       6.40e+01, 6.70e+01, 6.00e+01, 9.40e+01, 2.32e-01, 9.90e+01,
       6.24e-01, 9.50e+01, 4.10e-02, 2.92e-01, 1.10e-02, 8.00e+01,
       1.70e+00, 7.40e+01, 6.20e+01, 6.90e+01, 7.50e+01, 9.80e+01,
       8.50e+01, 8.20e+01, 9.60e+01, 8.70e+01, 7.10e+01, 8.60e+01,
       9.10e+01, 8.10e+01, 9.20e+01, 8.30e+01, 8.80e+01, 7.04e-01,
       8.62e-01, 8.99e-01, 3.78e-01, 2.66e-01, 3.75e-01, 1.30e+00,
       9.75e-01, 9.80e-01, 4.10e+00, 8.90e+01, 6.96e-01, 5.44e-01,
       5.25e-01, 9.20e-01, 7.79e-01, 8.53e-01, 7.20e-01, 7.13e-01,
       7.72e-01, 3.18e-01, 5.80e-02, 2.41e-01, 1.96e-01, 8.57e-01,
       5.10e-02, 9.53e-01, 8.65e-01, 2.51e-01, 9.30e-01, 5.40e-01,
       3.13e-01, 7.46e-01, 2.03e-01, 2.60e-02, 3.14e-01, 2.39e-01,
       3.71e-01, 2.20e-01, 7.30e-01, 7.56e-01, 9.10e-02, 2.93e-01,
       1.70e-02, 7.40e-02, 1.40e-02, 3.17e-01, 7.80e-02, 9.24e-01,
       9.02e-01, 8.18e-01, 8.10e-02, 9.39e-01, 1.69e-01, 4.50e-02,
       4.75e-01, 9.65e-01, 9.00e+01, 5.45e-01, 6.10e-02, 2.83e-01,
       6.55e-01, 7.14e-01, 9.30e-02, 8.72e-01, 1.21e-01, 3.22e-01,
       1.00e+00, 9.76e-01, 1.72e-01, 2.38e-01, 5.49e-01, 2.06e-01,
       9.54e-01, 4.44e-01, 7.17e-01, 2.10e-01, 6.09e-01, 3.08e-01,
       7.05e-01, 3.06e-01, 9.04e-01, 4.73e-01, 1.75e-01, 3.50e-01,
       3.83e-01, 4.54e-01, 4.21e-01, 7.00e-02, 8.12e-01, 4.42e-01,
       8.42e-01, 4.17e-01, 4.12e-01, 4.59e-01, 4.78e-01, 3.35e-01,
       7.82e-01, 7.21e-01, 4.30e-01, 4.29e-01, 1.92e-01, 2.00e-01,
       4.60e-01, 7.28e-01, 4.96e-01, 8.16e-01, 4.14e-01, 5.06e-01,
       8.87e-01, 6.13e-01, 2.43e-01, 5.69e-01, 7.78e-01, 6.83e-01,
       5.92e-01, 3.19e-01, 1.86e-01, 8.40e-01, 6.47e-01, 1.91e-01,
       3.73e-01, 4.37e-01, 5.98e-01, 7.16e-01, 5.85e-01, 9.82e-01,
       2.22e-01, 2.19e-01, 5.50e-02, 9.48e-01, 3.23e-01, 6.91e-01,
       5.11e-01, 9.51e-01, 9.63e-01, 2.50e-02, 5.54e-01, 3.51e-01,
       2.70e-02, 8.20e-02, 2.08e-01, 9.13e-01, 5.14e-01, 5.51e-01,
       2.90e-02, 1.03e-01, 8.98e-01, 7.43e-01, 1.16e-01, 1.53e-01,
       2.09e-01, 3.53e-01, 4.99e-01, 1.73e-01, 5.97e-01, 8.09e-01,
       1.22e-01, 4.11e-01, 4.00e-01, 8.01e-01, 7.87e-01, 2.37e-01,
       5.00e-02, 6.43e-01, 9.86e-01, 9.70e-02, 5.16e-01, 8.37e-01,
       7.80e-01, 9.61e-01, 2.69e-01, 2.00e-02, 4.98e-01, 6.00e-01,
       7.49e-01, 6.42e-01, 8.81e-01, 7.20e-02, 6.56e-01, 6.01e-01,
       2.21e-01, 2.28e-01, 1.08e-01, 9.40e-01, 1.76e-01, 3.30e-02,
       6.63e-01, 3.40e-02, 9.42e-01, 2.59e-01, 1.64e-01, 4.58e-01,
       2.45e-01, 6.29e-01, 2.80e-02, 2.88e-01, 7.75e-01, 7.85e-01,
       6.36e-01, 9.16e-01, 9.94e-01, 3.09e-01, 4.85e-01, 9.14e-01,
       9.03e-01, 6.08e-01, 5.00e-01, 5.40e-02, 5.62e-01, 8.47e-01,
       9.57e-01, 6.88e-01, 8.11e-01, 2.70e-01, 4.80e-02, 3.29e-01,
       5.23e-01, 9.21e-01, 8.74e-01, 9.81e-01, 7.84e-01, 2.80e-01,
       2.40e-02, 5.18e-01, 7.54e-01, 8.92e-01, 1.54e-01, 8.60e-01,
       3.64e-01, 3.87e-01, 6.26e-01, 1.61e-01, 8.79e-01, 3.90e-02,
       9.70e-01, 1.70e-01, 1.41e-01, 1.60e-01, 1.44e-01, 1.43e-01,
       1.90e-01, 3.76e-01, 1.93e-01, 2.46e-01, 7.30e-02, 6.58e-01,
       9.92e-01, 2.53e-01, 4.20e-01, 4.04e-01, 4.70e-01, 2.26e-01,
       2.40e-01, 8.90e-02, 2.34e-01, 2.57e-01, 8.61e-01, 4.67e-01,
       1.57e-01, 4.40e-02, 6.76e-01, 6.70e-02, 5.52e-01, 8.85e-01,
       1.02e+00, 5.82e-01, 6.19e-01])

In [42]:
df_copy["Size"]=df_copy["Size"].astype('str')

In [43]:
# replace M
df_copy['Size']= df_copy['Size'].str.replace("M","000")

In [44]:
# see changes
df_copy['Size']

0        19.0
1        14.0
2         8.7
3        25.0
4         2.8
         ...
10835    53.0
10836     3.6
10837     9.5
10838     nan
10839    19.0
Name: Size, Length: 10839, dtype: object

In [45]:
df_copy['Size'].unique()

array(['19.0', '14.0', '8.7', '25.0', '2.8', '5.6', '29.0', '33.0', '3.1',
       '28.0', '12.0', '20.0', '21.0', '37.0', '2.7', '5.5', '17.0',
       '39.0', '31.0', '4.2', '7.0', '23.0', '6.0', '6.1', '4.6', '9.2',
       '5.2', '11.0', '24.0', 'nan', '9.4', '15.0', '10.0', '1.2', '26.0',
       '8.0', '7.9', '56.0', '57.0', '35.0', '54.0', '0.201', '3.6',
       '5.7', '8.6', '2.4', '27.0', '2.5', '16.0', '3.4', '8.9', '3.9',
       '2.9', '38.0', '32.0', '5.4', '18.0', '1.1', '2.2', '4.5', '9.8',
       '52.0', '9.0', '6.7', '30.0', '2.6', '7.1', '3.7', '22.0', '7.4',
       '6.4', '3.2', '8.2', '9.9', '4.9', '9.5', '5.0', '5.9', '13.0',
       '73.0', '6.8', '3.5', '4.0', '2.3', '7.2', '2.1', '42.0', '7.3',
       '9.1', '55.0', '0.023', '6.5', '1.5', '7.5', '51.0', '41.0',
       '48.0', '8.5', '46.0', '8.3', '4.3', '4.7', '3.3', '40.0', '7.8',
       '8.8', '6.6', '5.1', '61.0', '66.0', '0.079', '8.4',
       '0.11800000000000001', '44.0', '0.695', '1.6', '6.2',
       '0.018000000000000002', '53.0', '1.4', '3.0', '5.8', '3.8', '9.6',
       '45.0', '63.0', '49.0', '77.0', '4.4', '4.8', '70.0', '6.9', '9.3',
       '8.1', '36.0', '84.0', '97.0', '2.0', '1.9', '1.8', '5.3', '47.0',
       '0.556', '0.526', '76.0', '7.6', '59.0', '9.7', '78.0', '72.0',
       '43.0', '7.7', '6.3', '0.33399999999999996', '34.0', '93.0',
       '65.0', '79.0', '100.0', '58.0', '50.0', '68.0', '64.0', '67.0',
       '60.0', '94.0', '0.23199999999999998', '99.0', '0.624', '95.0',
       '0.040999999999999995', '0.292', '0.011000000000000001', '80.0',
       '1.7', '74.0', '62.0', '69.0', '75.0', '98.0', '85.0', '82.0',
       '96.0', '87.0', '71.0', '86.0', '91.0', '81.0', '92.0', '83.0',
       '88.0', '0.7040000000000001', '0.862', '0.899',
       '0.37799999999999995', '0.266', '0.375', '1.3', '0.975', '0.98',
       '4.1', '89.0', '0.696', '0.544', '0.525', '0.92', '0.779', '0.853',
       '0.72', '0.713', '0.772', '0.318', '0.057999999999999996',
       '0.24100000000000002', '0.196', '0.857', '0.051', '0.953', '0.865',
       '0.251', '0.93', '0.54', '0.313', '0.746', '0.203',
       '0.026000000000000002', '0.314', '0.239', '0.371', '0.22', '0.73',
       '0.7559999999999999', '0.091', '0.293', '0.017',
       '0.07400000000000001', '0.013999999999999999', '0.317', '0.078',
       '0.924', '0.902', '0.818', '0.081', '0.9390000000000001',
       '0.16899999999999998', '0.045', '0.475', '0.965', '90.0', '0.545',
       '0.061', '0.28300000000000003', '0.655', '0.7140000000000001',
       '0.09300000000000001', '0.872', '0.121', '0.322', '1.0', '0.976',
       '0.172', '0.23800000000000002', '0.5489999999999999',
       '0.20600000000000002', '0.9540000000000001', '0.444',
       '0.7170000000000001', '0.21', '0.609', '0.308', '0.705', '0.306',
       '0.904', '0.473', '0.175', '0.35', '0.38299999999999995',
       '0.45399999999999996', '0.42100000000000004', '0.07', '0.812',
       '0.442', '0.8420000000000001', '0.41700000000000004',
       '0.41200000000000003', '0.45899999999999996', '0.478', '0.335',
       '0.782', '0.721', '0.43', '0.429', '0.192', '0.2', '0.46', '0.728',
       '0.496', '0.816', '0.414', '0.506', '0.887', '0.613', '0.243',
       '0.569', '0.778', '0.6829999999999999', '0.5920000000000001',
       '0.319', '0.18600000000000003', '0.84', '0.647', '0.191', '0.373',
       '0.43700000000000006', '0.598', '0.716', '0.585', '0.982', '0.222',
       '0.21899999999999997', '0.055', '0.948', '0.32299999999999995',
       '0.691', '0.511', '0.951', '0.963', '0.025', '0.5539999999999999',
       '0.35100000000000003', '0.027000000000000003',
       '0.08199999999999999', '0.20800000000000002', '0.9129999999999999',
       '0.514', '0.551', '0.028999999999999998', '0.10300000000000001',
       '0.898', '0.743', '0.11599999999999999', '0.153', '0.209', '0.353',
       '0.499', '0.17300000000000001', '0.597', '0.809', '0.122',
       '0.41100000000000003', '0.4', '0.8009999999999999', '0.787',
       '0.237', '0.05', '0.643', '0.986', '0.09699999999999999', '0.516',
       '0.8370000000000001', '0.78', '0.961', '0.26899999999999996',
       '0.02', '0.498', '0.6', '0.7490000000000001', '0.642',
       '0.8809999999999999', '0.07200000000000001', '0.6559999999999999',
       '0.601', '0.221', '0.228', '0.10800000000000001', '0.94',
       '0.17600000000000002', '0.033', '0.6629999999999999', '0.034',
       '0.9420000000000001', '0.259', '0.16399999999999998',
       '0.45799999999999996', '0.245', '0.629', '0.027999999999999997',
       '0.28800000000000003', '0.775', '0.785', '0.636',
       '0.9159999999999999', '0.9940000000000001', '0.309', '0.485',
       '0.914', '0.903', '0.608', '0.5', '0.054000000000000006', '0.562',
       '0.847', '0.9570000000000001', '0.688', '0.8109999999999999',
       '0.27', '0.048', '0.32899999999999996', '0.523',
       '0.9209999999999999', '0.8740000000000001', '0.981', '0.784',
       '0.28', '0.024', '0.518', '0.754', '0.892', '0.154', '0.86',
       '0.364', '0.387', '0.626', '0.161', '0.879', '0.039', '0.97',
       '0.17', '0.141', '0.16', '0.14400000000000002',
       '0.14300000000000002', '0.19', '0.376', '0.193',
       '0.24600000000000002', '0.073', '0.6579999999999999', '0.992',
       '0.253', '0.42', '0.40399999999999997', '0.47', '0.226', '0.24',
       '0.08900000000000001', '0.23399999999999999', '0.257', '0.861',
       '0.467', '0.157', '0.044000000000000004', '0.6759999999999999',
       '0.067', '0.552', '0.885', '1.02', '0.5820000000000001', '0.619'],
      dtype=object)

In [46]:
df_copy['Size']= df_copy['Size'].str.replace("k","")
df_copy['Size']

0        19.0
1        14.0
2         8.7
3        25.0
4         2.8
         ...
10835    53.0
10836     3.6
10837     9.5
10838     nan
10839    19.0
Name: Size, Length: 10839, dtype: object

In [47]:
df_copy['Size'].unique()

array(['19.0', '14.0', '8.7', '25.0', '2.8', '5.6', '29.0', '33.0', '3.1',
       '28.0', '12.0', '20.0', '21.0', '37.0', '2.7', '5.5', '17.0',
       '39.0', '31.0', '4.2', '7.0', '23.0', '6.0', '6.1', '4.6', '9.2',
       '5.2', '11.0', '24.0', 'nan', '9.4', '15.0', '10.0', '1.2', '26.0',
       '8.0', '7.9', '56.0', '57.0', '35.0', '54.0', '0.201', '3.6',
       '5.7', '8.6', '2.4', '27.0', '2.5', '16.0', '3.4', '8.9', '3.9',
       '2.9', '38.0', '32.0', '5.4', '18.0', '1.1', '2.2', '4.5', '9.8',
       '52.0', '9.0', '6.7', '30.0', '2.6', '7.1', '3.7', '22.0', '7.4',
       '6.4', '3.2', '8.2', '9.9', '4.9', '9.5', '5.0', '5.9', '13.0',
       '73.0', '6.8', '3.5', '4.0', '2.3', '7.2', '2.1', '42.0', '7.3',
       '9.1', '55.0', '0.023', '6.5', '1.5', '7.5', '51.0', '41.0',
       '48.0', '8.5', '46.0', '8.3', '4.3', '4.7', '3.3', '40.0', '7.8',
       '8.8', '6.6', '5.1', '61.0', '66.0', '0.079', '8.4',
       '0.11800000000000001', '44.0', '0.695', '1.6', '6.2',
       '0.018000000000000002', '53.0', '1.4', '3.0', '5.8', '3.8', '9.6',
       '45.0', '63.0', '49.0', '77.0', '4.4', '4.8', '70.0', '6.9', '9.3',
       '8.1', '36.0', '84.0', '97.0', '2.0', '1.9', '1.8', '5.3', '47.0',
       '0.556', '0.526', '76.0', '7.6', '59.0', '9.7', '78.0', '72.0',
       '43.0', '7.7', '6.3', '0.33399999999999996', '34.0', '93.0',
       '65.0', '79.0', '100.0', '58.0', '50.0', '68.0', '64.0', '67.0',
       '60.0', '94.0', '0.23199999999999998', '99.0', '0.624', '95.0',
       '0.040999999999999995', '0.292', '0.011000000000000001', '80.0',
       '1.7', '74.0', '62.0', '69.0', '75.0', '98.0', '85.0', '82.0',
       '96.0', '87.0', '71.0', '86.0', '91.0', '81.0', '92.0', '83.0',
       '88.0', '0.7040000000000001', '0.862', '0.899',
       '0.37799999999999995', '0.266', '0.375', '1.3', '0.975', '0.98',
       '4.1', '89.0', '0.696', '0.544', '0.525', '0.92', '0.779', '0.853',
       '0.72', '0.713', '0.772', '0.318', '0.057999999999999996',
       '0.24100000000000002', '0.196', '0.857', '0.051', '0.953', '0.865',
       '0.251', '0.93', '0.54', '0.313', '0.746', '0.203',
       '0.026000000000000002', '0.314', '0.239', '0.371', '0.22', '0.73',
       '0.7559999999999999', '0.091', '0.293', '0.017',
       '0.07400000000000001', '0.013999999999999999', '0.317', '0.078',
       '0.924', '0.902', '0.818', '0.081', '0.9390000000000001',
       '0.16899999999999998', '0.045', '0.475', '0.965', '90.0', '0.545',
       '0.061', '0.28300000000000003', '0.655', '0.7140000000000001',
       '0.09300000000000001', '0.872', '0.121', '0.322', '1.0', '0.976',
       '0.172', '0.23800000000000002', '0.5489999999999999',
       '0.20600000000000002', '0.9540000000000001', '0.444',
       '0.7170000000000001', '0.21', '0.609', '0.308', '0.705', '0.306',
       '0.904', '0.473', '0.175', '0.35', '0.38299999999999995',
       '0.45399999999999996', '0.42100000000000004', '0.07', '0.812',
       '0.442', '0.8420000000000001', '0.41700000000000004',
       '0.41200000000000003', '0.45899999999999996', '0.478', '0.335',
       '0.782', '0.721', '0.43', '0.429', '0.192', '0.2', '0.46', '0.728',
       '0.496', '0.816', '0.414', '0.506', '0.887', '0.613', '0.243',
       '0.569', '0.778', '0.6829999999999999', '0.5920000000000001',
       '0.319', '0.18600000000000003', '0.84', '0.647', '0.191', '0.373',
       '0.43700000000000006', '0.598', '0.716', '0.585', '0.982', '0.222',
       '0.21899999999999997', '0.055', '0.948', '0.32299999999999995',
       '0.691', '0.511', '0.951', '0.963', '0.025', '0.5539999999999999',
       '0.35100000000000003', '0.027000000000000003',
       '0.08199999999999999', '0.20800000000000002', '0.9129999999999999',
       '0.514', '0.551', '0.028999999999999998', '0.10300000000000001',
       '0.898', '0.743', '0.11599999999999999', '0.153', '0.209', '0.353',
       '0.499', '0.17300000000000001', '0.597', '0.809', '0.122',
       '0.41100000000000003', '0.4', '0.8009999999999999', '0.787',
       '0.237', '0.05', '0.643', '0.986', '0.09699999999999999', '0.516',
       '0.8370000000000001', '0.78', '0.961', '0.26899999999999996',
       '0.02', '0.498', '0.6', '0.7490000000000001', '0.642',
       '0.8809999999999999', '0.07200000000000001', '0.6559999999999999',
       '0.601', '0.221', '0.228', '0.10800000000000001', '0.94',
       '0.17600000000000002', '0.033', '0.6629999999999999', '0.034',
       '0.9420000000000001', '0.259', '0.16399999999999998',
       '0.45799999999999996', '0.245', '0.629', '0.027999999999999997',
       '0.28800000000000003', '0.775', '0.785', '0.636',
       '0.9159999999999999', '0.9940000000000001', '0.309', '0.485',
       '0.914', '0.903', '0.608', '0.5', '0.054000000000000006', '0.562',
       '0.847', '0.9570000000000001', '0.688', '0.8109999999999999',
       '0.27', '0.048', '0.32899999999999996', '0.523',
       '0.9209999999999999', '0.8740000000000001', '0.981', '0.784',
       '0.28', '0.024', '0.518', '0.754', '0.892', '0.154', '0.86',
       '0.364', '0.387', '0.626', '0.161', '0.879', '0.039', '0.97',
       '0.17', '0.141', '0.16', '0.14400000000000002',
       '0.14300000000000002', '0.19', '0.376', '0.193',
       '0.24600000000000002', '0.073', '0.6579999999999999', '0.992',
       '0.253', '0.42', '0.40399999999999997', '0.47', '0.226', '0.24',
       '0.08900000000000001', '0.23399999999999999', '0.257', '0.861',
       '0.467', '0.157', '0.044000000000000004', '0.6759999999999999',
       '0.067', '0.552', '0.885', '1.02', '0.5820000000000001', '0.619'],
      dtype=object)

In [48]:
df_copy["Size"]=df_copy["Size"].str.replace("Varies with device", str(np.nan))

In [49]:
df_copy["Size"].unique()

array(['19.0', '14.0', '8.7', '25.0', '2.8', '5.6', '29.0', '33.0', '3.1',
       '28.0', '12.0', '20.0', '21.0', '37.0', '2.7', '5.5', '17.0',
       '39.0', '31.0', '4.2', '7.0', '23.0', '6.0', '6.1', '4.6', '9.2',
       '5.2', '11.0', '24.0', 'nan', '9.4', '15.0', '10.0', '1.2', '26.0',
       '8.0', '7.9', '56.0', '57.0', '35.0', '54.0', '0.201', '3.6',
       '5.7', '8.6', '2.4', '27.0', '2.5', '16.0', '3.4', '8.9', '3.9',
       '2.9', '38.0', '32.0', '5.4', '18.0', '1.1', '2.2', '4.5', '9.8',
       '52.0', '9.0', '6.7', '30.0', '2.6', '7.1', '3.7', '22.0', '7.4',
       '6.4', '3.2', '8.2', '9.9', '4.9', '9.5', '5.0', '5.9', '13.0',
       '73.0', '6.8', '3.5', '4.0', '2.3', '7.2', '2.1', '42.0', '7.3',
       '9.1', '55.0', '0.023', '6.5', '1.5', '7.5', '51.0', '41.0',
       '48.0', '8.5', '46.0', '8.3', '4.3', '4.7', '3.3', '40.0', '7.8',
       '8.8', '6.6', '5.1', '61.0', '66.0', '0.079', '8.4',
       '0.11800000000000001', '44.0', '0.695', '1.6', '6.2',
       '0.018000000000000002', '53.0', '1.4', '3.0', '5.8', '3.8', '9.6',
       '45.0', '63.0', '49.0', '77.0', '4.4', '4.8', '70.0', '6.9', '9.3',
       '8.1', '36.0', '84.0', '97.0', '2.0', '1.9', '1.8', '5.3', '47.0',
       '0.556', '0.526', '76.0', '7.6', '59.0', '9.7', '78.0', '72.0',
       '43.0', '7.7', '6.3', '0.33399999999999996', '34.0', '93.0',
       '65.0', '79.0', '100.0', '58.0', '50.0', '68.0', '64.0', '67.0',
       '60.0', '94.0', '0.23199999999999998', '99.0', '0.624', '95.0',
       '0.040999999999999995', '0.292', '0.011000000000000001', '80.0',
       '1.7', '74.0', '62.0', '69.0', '75.0', '98.0', '85.0', '82.0',
       '96.0', '87.0', '71.0', '86.0', '91.0', '81.0', '92.0', '83.0',
       '88.0', '0.7040000000000001', '0.862', '0.899',
       '0.37799999999999995', '0.266', '0.375', '1.3', '0.975', '0.98',
       '4.1', '89.0', '0.696', '0.544', '0.525', '0.92', '0.779', '0.853',
       '0.72', '0.713', '0.772', '0.318', '0.057999999999999996',
       '0.24100000000000002', '0.196', '0.857', '0.051', '0.953', '0.865',
       '0.251', '0.93', '0.54', '0.313', '0.746', '0.203',
       '0.026000000000000002', '0.314', '0.239', '0.371', '0.22', '0.73',
       '0.7559999999999999', '0.091', '0.293', '0.017',
       '0.07400000000000001', '0.013999999999999999', '0.317', '0.078',
       '0.924', '0.902', '0.818', '0.081', '0.9390000000000001',
       '0.16899999999999998', '0.045', '0.475', '0.965', '90.0', '0.545',
       '0.061', '0.28300000000000003', '0.655', '0.7140000000000001',
       '0.09300000000000001', '0.872', '0.121', '0.322', '1.0', '0.976',
       '0.172', '0.23800000000000002', '0.5489999999999999',
       '0.20600000000000002', '0.9540000000000001', '0.444',
       '0.7170000000000001', '0.21', '0.609', '0.308', '0.705', '0.306',
       '0.904', '0.473', '0.175', '0.35', '0.38299999999999995',
       '0.45399999999999996', '0.42100000000000004', '0.07', '0.812',
       '0.442', '0.8420000000000001', '0.41700000000000004',
       '0.41200000000000003', '0.45899999999999996', '0.478', '0.335',
       '0.782', '0.721', '0.43', '0.429', '0.192', '0.2', '0.46', '0.728',
       '0.496', '0.816', '0.414', '0.506', '0.887', '0.613', '0.243',
       '0.569', '0.778', '0.6829999999999999', '0.5920000000000001',
       '0.319', '0.18600000000000003', '0.84', '0.647', '0.191', '0.373',
       '0.43700000000000006', '0.598', '0.716', '0.585', '0.982', '0.222',
       '0.21899999999999997', '0.055', '0.948', '0.32299999999999995',
       '0.691', '0.511', '0.951', '0.963', '0.025', '0.5539999999999999',
       '0.35100000000000003', '0.027000000000000003',
       '0.08199999999999999', '0.20800000000000002', '0.9129999999999999',
       '0.514', '0.551', '0.028999999999999998', '0.10300000000000001',
       '0.898', '0.743', '0.11599999999999999', '0.153', '0.209', '0.353',
       '0.499', '0.17300000000000001', '0.597', '0.809', '0.122',
       '0.41100000000000003', '0.4', '0.8009999999999999', '0.787',
       '0.237', '0.05', '0.643', '0.986', '0.09699999999999999', '0.516',
       '0.8370000000000001', '0.78', '0.961', '0.26899999999999996',
       '0.02', '0.498', '0.6', '0.7490000000000001', '0.642',
       '0.8809999999999999', '0.07200000000000001', '0.6559999999999999',
       '0.601', '0.221', '0.228', '0.10800000000000001', '0.94',
       '0.17600000000000002', '0.033', '0.6629999999999999', '0.034',
       '0.9420000000000001', '0.259', '0.16399999999999998',
       '0.45799999999999996', '0.245', '0.629', '0.027999999999999997',
       '0.28800000000000003', '0.775', '0.785', '0.636',
       '0.9159999999999999', '0.9940000000000001', '0.309', '0.485',
       '0.914', '0.903', '0.608', '0.5', '0.054000000000000006', '0.562',
       '0.847', '0.9570000000000001', '0.688', '0.8109999999999999',
       '0.27', '0.048', '0.32899999999999996', '0.523',
       '0.9209999999999999', '0.8740000000000001', '0.981', '0.784',
       '0.28', '0.024', '0.518', '0.754', '0.892', '0.154', '0.86',
       '0.364', '0.387', '0.626', '0.161', '0.879', '0.039', '0.97',
       '0.17', '0.141', '0.16', '0.14400000000000002',
       '0.14300000000000002', '0.19', '0.376', '0.193',
       '0.24600000000000002', '0.073', '0.6579999999999999', '0.992',
       '0.253', '0.42', '0.40399999999999997', '0.47', '0.226', '0.24',
       '0.08900000000000001', '0.23399999999999999', '0.257', '0.861',
       '0.467', '0.157', '0.044000000000000004', '0.6759999999999999',
       '0.067', '0.552', '0.885', '1.02', '0.5820000000000001', '0.619'],
      dtype=object)

# or we can drope this row

In [50]:
df_copy['Size']= df_copy['Size'].astype("float")

In [51]:
df_copy['Size'].dtype

dtype('float64')

In [52]:
df_copy['Size'].isnull().sum()

1695

# there 1695 null values in 'Size' column

In [53]:
df_copy['Size'].head()

0    19.0
1    14.0
2     8.7
3    25.0
4     2.8
Name: Size, dtype: float64

In [54]:
df_copy['Size'][2]

8.7

In [55]:
df_copy['Size'][2]*1000

8700.0

In [56]:
# do iteration to change all values
for i in df_copy['Size']:
    if i<11:
        df_copy['Size']=df_copy['Size'].replace(i,i*1000)

In [57]:
df_copy['Size'].head()

0      19.0
1      14.0
2    8700.0
3      25.0
4    2800.0
Name: Size, dtype: float64

In [58]:
df_copy['Size'].unique()

array([   19.,    14.,  8700.,    25.,  2800.,  5600.,    29.,    33.,
        3100.,    28.,    12.,    20.,    21.,    37.,  2700.,  5500.,
          17.,    39.,    31.,  4200.,  7000.,    23.,  6000.,  6100.,
        4600.,  9200.,  5200.,    11.,    24.,    nan,  9400.,    15.,
       10000.,  1200.,    26.,  8000.,  7900.,    56.,    57.,    35.,
          54.,   201.,  3600.,  5700.,  8600.,  2400.,    27.,  2500.,
          16.,  3400.,  8900.,  3900.,  2900.,    38.,    32.,  5400.,
          18.,  1100.,  2200.,  4500.,  9800.,    52.,  9000.,  6700.,
          30.,  2600.,  7100.,  3700.,    22.,  7400.,  6400.,  3200.,
        8200.,  9900.,  4900.,  9500.,  5000.,  5900.,    13.,    73.,
        6800.,  3500.,  4000.,  2300.,  7200.,  2100.,    42.,  7300.,
        9100.,    55.,  6500.,  1500.,  7500.,    51.,    41.,    48.,
        8500.,    46.,  8300.,  4300.,  4700.,  3300.,    40.,  7800.,
        8800.,  6600.,  5100.,    61.,    66.,    79.,  8400.,   118.,
          44.,   695.,  1600.,  6200.,    18.,    53.,  1400.,  3000.,
        5800.,  3800.,  9600.,    45.,    63.,    49.,    77.,  4400.,
        4800.,    70.,  6900.,  9300.,  8100.,    36.,    84.,    97.,
        2000.,  1900.,  1800.,  5300.,    47.,   556.,   526.,    76.,
        7600.,    59.,  9700.,    78.,    72.,    43.,  7700.,  6300.,
         334.,    34.,    93.,    65.,   100.,    58.,    50.,    68.,
          64.,    67.,    60.,    94.,   232.,    99.,   624.,    95.,
          41.,   292.,    11.,    80.,  1700.,    74.,    62.,    69.,
          75.,    98.,    85.,    82.,    96.,    87.,    71.,    86.,
          91.,    81.,    92.,    83.,    88.,   704.,   862.,   899.,
         378.,   266.,   375.,  1300.,   975.,   980.,  4100.,    89.,
         696.,   544.,   525.,   920.,   779.,   853.,   720.,   713.,
         772.,   318.,    58.,   241.,   196.,   857.,   953.,   865.,
         251.,   930.,   540.,   313.,   746.,   203.,    26.,   314.,
         239.,   371.,   220.,   730.,   756.,   293.,    74.,    14.,
         317.,   924.,   902.,   818.,   939.,   169.,   475.,   965.,
          90.,   545.,   283.,   655.,   714.,    93.,   872.,   121.,
         322.,  1000.,   976.,   172.,   238.,   549.,   206.,   954.,
         444.,   717.,   210.,   609.,   308.,   705.,   306.,   904.,
         473.,   175.,   350.,   383.,   454.,   421.,   812.,   442.,
         842.,   417.,   412.,   459.,   478.,   335.,   782.,   721.,
         430.,   429.,   192.,   200.,   460.,   728.,   496.,   816.,
         414.,   506.,   887.,   613.,   243.,   569.,   778.,   683.,
         592.,   319.,   186.,   840.,   647.,   191.,   373.,   437.,
         598.,   716.,   585.,   982.,   222.,   219.,   948.,   323.,
         691.,   511.,   951.,   963.,   554.,   351.,    27.,    82.,
         208.,   913.,   514.,   551.,    29.,   103.,   898.,   743.,
         116.,   153.,   209.,   353.,   499.,   173.,   597.,   809.,
         122.,   411.,   400.,   801.,   787.,   237.,   643.,   986.,
          97.,   516.,   837.,   780.,   961.,   269.,   498.,   600.,
         749.,   642.,   881.,    72.,   656.,   601.,   221.,   228.,
         108.,   940.,   176.,   663.,   942.,   259.,   164.,   458.,
         245.,   629.,    28.,   288.,   775.,   785.,   636.,   916.,
         994.,   309.,   485.,   914.,   903.,   608.,   500.,    54.,
         562.,   847.,   957.,   688.,   811.,   270.,   329.,   523.,
         921.,   874.,   981.,   784.,   280.,   518.,   754.,   892.,
         154.,   860.,   364.,   387.,   626.,   161.,   879.,   970.,
         170.,   141.,   160.,   144.,   143.,   190.,   376.,   193.,
         246.,   658.,   992.,   253.,   420.,   404.,   470.,   226.,
         240.,    89.,   234.,   257.,   861.,   467.,   157.,    44.,
         676.,   552.,   885.,  1020.,   582.,   619.])

In [59]:
df_copy['Size'].dtype

dtype('float64')

In [60]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10839 entries, 0 to 10839
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  object
 1   Category        10839 non-null  object
 2   Rating          9365 non-null   float64
 3   Reviews         10839 non-null  int32
 4   Size            9144 non-null   float64
 5   Installs        10839 non-null  int64
 6   Type            10838 non-null  object
 7   Price           10839 non-null  float64
 8   Content Rating  10839 non-null  object
 9   Genres          10839 non-null  object
 10  Last Updated    10839 non-null  object
 11  Current Ver     10831 non-null  object
 12  Android Ver     10837 non-null  object
 13  day             10839 non-null  int64
 14  month           10839 non-null  int64
 15  yrar            10839 non-null  int64
dtypes: float64(3), int32(1), int64(4), object(8)
memory usage: 1.7+ MB

In [61]:
# scale the value in paeticular range
df_copy['Size']=df_copy['Size']/1000

In [62]:
df_copy['Size']

0        0.019
1        0.014
2        8.700
3        0.025
4        2.800
         ...
10835    0.053
10836    3.600
10837    9.500
10838      NaN
10839    0.019
Name: Size, Length: 10839, dtype: float64

In [63]:
df_copy['Size'].unique()

array([ 0.019,  0.014,  8.7  ,  0.025,  2.8  ,  5.6  ,  0.029,  0.033,
        3.1  ,  0.028,  0.012,  0.02 ,  0.021,  0.037,  2.7  ,  5.5  ,
        0.017,  0.039,  0.031,  4.2  ,  7.   ,  0.023,  6.   ,  6.1  ,
        4.6  ,  9.2  ,  5.2  ,  0.011,  0.024,    nan,  9.4  ,  0.015,
       10.   ,  1.2  ,  0.026,  8.   ,  7.9  ,  0.056,  0.057,  0.035,
        0.054,  0.201,  3.6  ,  5.7  ,  8.6  ,  2.4  ,  0.027,  2.5  ,
        0.016,  3.4  ,  8.9  ,  3.9  ,  2.9  ,  0.038,  0.032,  5.4  ,
        0.018,  1.1  ,  2.2  ,  4.5  ,  9.8  ,  0.052,  9.   ,  6.7  ,
        0.03 ,  2.6  ,  7.1  ,  3.7  ,  0.022,  7.4  ,  6.4  ,  3.2  ,
        8.2  ,  9.9  ,  4.9  ,  9.5  ,  5.   ,  5.9  ,  0.013,  0.073,
        6.8  ,  3.5  ,  4.   ,  2.3  ,  7.2  ,  2.1  ,  0.042,  7.3  ,
        9.1  ,  0.055,  6.5  ,  1.5  ,  7.5  ,  0.051,  0.041,  0.048,
        8.5  ,  0.046,  8.3  ,  4.3  ,  4.7  ,  3.3  ,  0.04 ,  7.8  ,
        8.8  ,  6.6  ,  5.1  ,  0.061,  0.066,  0.079,  8.4  ,  0.118,
        0.044,  0.695,  1.6  ,  6.2  ,  0.018,  0.053,  1.4  ,  3.   ,
        5.8  ,  3.8  ,  9.6  ,  0.045,  0.063,  0.049,  0.077,  4.4  ,
        4.8  ,  0.07 ,  6.9  ,  9.3  ,  8.1  ,  0.036,  0.084,  0.097,
        2.   ,  1.9  ,  1.8  ,  5.3  ,  0.047,  0.556,  0.526,  0.076,
        7.6  ,  0.059,  9.7  ,  0.078,  0.072,  0.043,  7.7  ,  6.3  ,
        0.334,  0.034,  0.093,  0.065,  0.1  ,  0.058,  0.05 ,  0.068,
        0.064,  0.067,  0.06 ,  0.094,  0.232,  0.099,  0.624,  0.095,
        0.041,  0.292,  0.011,  0.08 ,  1.7  ,  0.074,  0.062,  0.069,
        0.075,  0.098,  0.085,  0.082,  0.096,  0.087,  0.071,  0.086,
        0.091,  0.081,  0.092,  0.083,  0.088,  0.704,  0.862,  0.899,
        0.378,  0.266,  0.375,  1.3  ,  0.975,  0.98 ,  4.1  ,  0.089,
        0.696,  0.544,  0.525,  0.92 ,  0.779,  0.853,  0.72 ,  0.713,
        0.772,  0.318,  0.058,  0.241,  0.196,  0.857,  0.953,  0.865,
        0.251,  0.93 ,  0.54 ,  0.313,  0.746,  0.203,  0.026,  0.314,
        0.239,  0.371,  0.22 ,  0.73 ,  0.756,  0.293,  0.074,  0.014,
        0.317,  0.924,  0.902,  0.818,  0.939,  0.169,  0.475,  0.965,
        0.09 ,  0.545,  0.283,  0.655,  0.714,  0.093,  0.872,  0.121,
        0.322,  1.   ,  0.976,  0.172,  0.238,  0.549,  0.206,  0.954,
        0.444,  0.717,  0.21 ,  0.609,  0.308,  0.705,  0.306,  0.904,
        0.473,  0.175,  0.35 ,  0.383,  0.454,  0.421,  0.812,  0.442,
        0.842,  0.417,  0.412,  0.459,  0.478,  0.335,  0.782,  0.721,
        0.43 ,  0.429,  0.192,  0.2  ,  0.46 ,  0.728,  0.496,  0.816,
        0.414,  0.506,  0.887,  0.613,  0.243,  0.569,  0.778,  0.683,
        0.592,  0.319,  0.186,  0.84 ,  0.647,  0.191,  0.373,  0.437,
        0.598,  0.716,  0.585,  0.982,  0.222,  0.219,  0.948,  0.323,
        0.691,  0.511,  0.951,  0.963,  0.554,  0.351,  0.027,  0.082,
        0.208,  0.913,  0.514,  0.551,  0.029,  0.103,  0.898,  0.743,
        0.116,  0.153,  0.209,  0.353,  0.499,  0.173,  0.597,  0.809,
        0.122,  0.411,  0.4  ,  0.801,  0.787,  0.237,  0.643,  0.986,
        0.097,  0.516,  0.837,  0.78 ,  0.961,  0.269,  0.498,  0.6  ,
        0.749,  0.642,  0.881,  0.072,  0.656,  0.601,  0.221,  0.228,
        0.108,  0.94 ,  0.176,  0.663,  0.942,  0.259,  0.164,  0.458,
        0.245,  0.629,  0.028,  0.288,  0.775,  0.785,  0.636,  0.916,
        0.994,  0.309,  0.485,  0.914,  0.903,  0.608,  0.5  ,  0.054,
        0.562,  0.847,  0.957,  0.688,  0.811,  0.27 ,  0.329,  0.523,
        0.921,  0.874,  0.981,  0.784,  0.28 ,  0.518,  0.754,  0.892,
        0.154,  0.86 ,  0.364,  0.387,  0.626,  0.161,  0.879,  0.97 ,
        0.17 ,  0.141,  0.16 ,  0.144,  0.143,  0.19 ,  0.376,  0.193,
        0.246,  0.658,  0.992,  0.253,  0.42 ,  0.404,  0.47 ,  0.226,
        0.24 ,  0.089,  0.234,  0.257,  0.861,  0.467,  0.157,  0.044,
        0.676,  0.552,  0.885,  1.02 ,  0.582,  0.619])

In [64]:
df_copy.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver', 'day', 'month', 'yrar'],
      dtype='object')

In [65]:
df_copy.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,yrar
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,0.019,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,7,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,0.014,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,15,1,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.700,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,1,8,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,0.025,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,8,6,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.800,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,20,6,2018

In [66]:
df_copy['Installs'].dtype

dtype('int64')

In [67]:
df_copy['Installs'].unique()

array([     10000,     500000,    5000000,   50000000,     100000,
            50000,    1000000,   10000000,       5000,  100000000,
       1000000000,       1000,  500000000,         50,        100,
              500,         10,          1,          5,          0],
      dtype=int64)

In [68]:
df_copy['Price'].unique()

array([  0.  ,   4.99,   3.99,   6.99,   1.49,   2.99,   7.99,   5.99,
         3.49,   1.99,   9.99,   7.49,   0.99,   9.  ,   5.49,  10.  ,
        24.99,  11.99,  79.99,  16.99,  14.99,   1.  ,  29.99,  12.99,
         2.49,  10.99,   1.5 ,  19.99,  15.99,  33.99,  74.99,  39.99,
         3.95,   4.49,   1.7 ,   8.99,   2.  ,   3.88,  25.99, 399.99,
        17.99, 400.  ,   3.02,   1.76,   4.84,   4.77,   1.61,   2.5 ,
         1.59,   6.49,   1.29,   5.  ,  13.99, 299.99, 379.99,  37.99,
        18.99, 389.99,  19.9 ,   8.49,   1.75,  14.  ,   4.85,  46.99,
       109.99, 154.99,   3.08,   2.59,   4.8 ,   1.96,  19.4 ,   3.9 ,
         4.59,  15.46,   3.04,   4.29,   2.6 ,   3.28,   4.6 ,  28.99,
         2.95,   2.9 ,   1.97, 200.  ,  89.99,   2.56,  30.99,   3.61,
       394.99,   1.26,   1.2 ,   1.04])

# focus on above two columns we need to remove +, "," ,$ symbol

In [69]:
charater_remove=['+', ",", "$",]
columns_clean= ["Installs","Price"]
for i in charater_remove:   # which charates need to be remove
    for col in columns_clean:    # columns to be clean
        df_copy[col]=df_copy[col].str.replace(i, '')

AttributeError: Can only use .str accessor with string values!

In [75]:
df_copy["Installs"]=df_copy["Installs"].astype('str')
df_copy["Price"]=df_copy["Price"].astype('str')

In [76]:
charater_remove=['+', ",", "$",]
columns_clean= ["Installs","Price"]
for i in charater_remove:   # which charates need to be remove
    for col in columns_clean:    # columns to be clean
        df_copy[col]=df_copy[col].str.replace(i, '')

In [77]:
df_copy["Installs"].unique()

array(['10000', '500000', '5000000', '50000000', '100000', '50000',
       '1000000', '10000000', '5000', '100000000', '1000000000', '1000',
       '500000000', '50', '100', '500', '10', '1', '5', '0'], dtype=object)

In [78]:
df_copy["Price"].unique()

array(['0.0', '4.99', '3.99', '6.99', '1.49', '2.99', '7.99', '5.99',
       '3.49', '1.99', '9.99', '7.49', '0.99', '9.0', '5.49', '10.0',
       '24.99', '11.99', '79.99', '16.99', '14.99', '1.0', '29.99',
       '12.99', '2.49', '10.99', '1.5', '19.99', '15.99', '33.99',
       '74.99', '39.99', '3.95', '4.49', '1.7', '8.99', '2.0', '3.88',
       '25.99', '399.99', '17.99', '400.0', '3.02', '1.76', '4.84',
       '4.77', '1.61', '2.5', '1.59', '6.49', '1.29', '5.0', '13.99',
       '299.99', '379.99', '37.99', '18.99', '389.99', '19.9', '8.49',
       '1.75', '14.0', '4.85', '46.99', '109.99', '154.99', '3.08',
       '2.59', '4.8', '1.96', '19.4', '3.9', '4.59', '15.46', '3.04',
       '4.29', '2.6', '3.28', '4.6', '28.99', '2.95', '2.9', '1.97',
       '200.0', '89.99', '2.56', '30.99', '3.61', '394.99', '1.26', '1.2',
       '1.04'], dtype=object)

In [79]:
df_copy["Price"]

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
10835    0.0
10836    0.0
10837    0.0
10838    0.0
10839    0.0
Name: Price, Length: 10839, dtype: object

In [80]:
df_copy["Installs"]=df_copy["Installs"].astype('int')

In [81]:
df_copy["Price"]=df_copy["Price"].astype('float')

In [82]:
df_copy["Price"].dtype

dtype('float64')

In [83]:
df_copy["Installs"].dtype

dtype('int32')

In [84]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10839 entries, 0 to 10839
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  object
 1   Category        10839 non-null  object
 2   Rating          9365 non-null   float64
 3   Reviews         10839 non-null  object
 4   Size            9144 non-null   float64
 5   Installs        10839 non-null  int32
 6   Type            10838 non-null  object
 7   Price           10839 non-null  float64
 8   Content Rating  10839 non-null  object
 9   Genres          10839 non-null  object
 10  Last Updated    10839 non-null  object
 11  Current Ver     10831 non-null  object
 12  Android Ver     10837 non-null  object
 13  day             10839 non-null  int64
 14  month           10839 non-null  int64
 15  yrar            10839 non-null  int64
dtypes: float64(3), int32(1), int64(3), object(9)
memory usage: 1.7+ MB

# Work on 'Last Updated' column which is object

In [85]:
df_copy["Last Updated"]

0        2018-01-07
1        2018-01-15
2        2018-08-01
3        2018-06-08
4        2018-06-20
            ...
10835    2017-07-25
10836    2018-07-06
10837    2017-01-20
10838    2015-01-19
10839    2018-07-25
Name: Last Updated, Length: 10839, dtype: object

In [86]:
df_copy["Last Updated"].unique()

array(['2018-01-07', '2018-01-15', '2018-08-01', ..., '2014-01-20',
       '2014-02-16', '2014-03-23'], dtype=object)

# Break into date , Month, year

In [87]:
pd.to_datetime(df_copy["Last Updated"])

0       2018-01-07
1       2018-01-15
2       2018-08-01
3       2018-06-08
4       2018-06-20
           ...
10835   2017-07-25
10836   2018-07-06
10837   2017-01-20
10838   2015-01-19
10839   2018-07-25
Name: Last Updated, Length: 10839, dtype: datetime64[ns]

In [88]:
df_copy["Last Updated"]=pd.to_datetime(df_copy["Last Updated"])

In [89]:
df_copy.head(3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,yrar
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,0.019,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,7,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,0.014,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,15,1,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.700,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,1,8,2018

In [90]:
# create new column of day
df_copy["day"]=df_copy["Last Updated"].dt.day

In [91]:
df_copy["day"]

0         7
1        15
2         1
3         8
4        20
         ..
10835    25
10836     6
10837    20
10838    19
10839    25
Name: day, Length: 10839, dtype: int64

In [92]:
# create new column of month
df_copy["month"]=df_copy["Last Updated"].dt.month

In [93]:
df_copy["month"]

0        1
1        1
2        8
3        6
4        6
        ..
10835    7
10836    7
10837    1
10838    1
10839    7
Name: month, Length: 10839, dtype: int64

In [94]:
# create new column of year
df_copy["yrar"]=df_copy["Last Updated"].dt.year

In [95]:
df_copy["yrar"]

0        2018
1        2018
2        2018
3        2018
4        2018
         ...
10835    2017
10836    2018
10837    2017
10838    2015
10839    2018
Name: yrar, Length: 10839, dtype: int64

In [96]:
df_copy.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,yrar
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,0.019,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,7,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,0.014,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,15,1,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.700,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,1,8,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,0.025,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,8,6,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.800,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,20,6,2018

In [97]:
df_copy["yrar"].dtype

dtype('int64')

In [98]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,yrar
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,7,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,15,1,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,1,8,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,8,6,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,20,6,2018

In [99]:
# save the  clean data into new csv
df_copy.to_csv ("clean_gpaydata.csv",index= False)

In [100]:
df1=pd.read_csv('clean_gpaydata.csv')
df1.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,day,month,yrar
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,0.019,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,7,1,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,0.014,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,15,1,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.700,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,1,8,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,0.025,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,8,6,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.800,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,20,6,2018

# END